name: Sphinx Docs

on:
  push:
    paths:
      - 'docs/**'
      - 'sft2d/**'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme myst_parser nbsphinx pypandoc ipykernel sphinx-autodoc-typehints

      - name: Install sft2d package
        run: pip install -e .

      - name: Cache Sphinx _build
        uses: actions/cache@v3
        with:
          path: docs/_build
          key: ${{ runner.os }}-sphinx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-sphinx-

      - name: Build Sphinx docs
        run: sphinx-build -b html . docs/_build
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
          force_orphan: true

